import type { DebugSession } from "./bandfix-types";

function fmtTime(ts: number): string {
  return new Date(ts).toISOString().replace("T", " ").replace("Z", " UTC");
}

function fmtDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
}

export function buildMarkdownReport(session: DebugSession): string {
  const { input, bugReport, fix, review, messages } = session;
  const lines: string[] = [];

  lines.push(`# BandFix AI — Debug Report`);
  lines.push("");
  lines.push(`**Session:** \`${session.id}\``);
  lines.push(`**Title:** ${input.title}`);
  lines.push(`**Language:** ${input.language}`);
  lines.push(`**Started:** ${fmtTime(session.createdAt)}`);
  lines.push(`**Duration:** ${fmtDuration(session.durationMs)}`);
  lines.push(`**Status:** ${session.status}${session.error ? ` (${session.error})` : ""}`);
  lines.push("");

  lines.push(`## 1. Original Input`);
  lines.push("");
  lines.push(`**Error / observed behaviour:**`);
  lines.push("```");
  lines.push(input.error || "(none provided)");
  lines.push("```");
  lines.push("");
  lines.push(`**Original code:**`);
  lines.push("```" + (input.language || ""));
  lines.push(input.code);
  lines.push("```");
  lines.push("");

  lines.push(`## 2. Bug Finder`);
  lines.push("");
  if (bugReport) {
    lines.push(`- **Root cause:** ${bugReport.rootCause}`);
    lines.push(`- **Severity:** ${bugReport.severity}`);
    lines.push("");
    lines.push(bugReport.explanation);
  } else {
    lines.push("_No bug report produced._");
  }
  lines.push("");

  lines.push(`## 3. Fix Generator`);
  lines.push("");
  if (fix) {
    lines.push(`**Changes (${fix.changes.length}):**`);
    for (const c of fix.changes) lines.push(`- ${c}`);
    lines.push("");
    lines.push(`**Fixed code:**`);
    lines.push("```" + (input.language || ""));
    lines.push(fix.fixedCode);
    lines.push("```");
  } else {
    lines.push("_No fix produced._");
  }
  lines.push("");

  lines.push(`## 4. Reviewer`);
  lines.push("");
  if (review) {
    lines.push(`- **Status:** ${review.status}`);
    lines.push(`- **Score:** ${review.score}/100`);
    lines.push(`- **Security:** ${review.securityNote}`);
    lines.push(`- **Performance:** ${review.performanceNote}`);
    lines.push("");
    lines.push(`**Recommendation:** ${review.recommendation}`);
  } else {
    lines.push("_No review produced._");
  }
  lines.push("");

  lines.push(`## 5. Band Channel Transcript`);
  lines.push("");
  lines.push(`| # | Time | Channel | From → To | Type | Message |`);
  lines.push(`|---|------|---------|-----------|------|---------|`);
  messages.forEach((m, i) => {
    const route = m.to ? `${m.from} → ${m.to}` : m.from;
    const text = m.text.replace(/\|/g, "\\|").replace(/\n/g, " ");
    lines.push(`| ${i + 1} | ${fmtTime(m.timestamp)} | \`${m.channel}\` | ${route} | ${m.type} | ${text} |`);
  });
  lines.push("");
  lines.push(`---`);
  lines.push(`_Generated by BandFix AI · multi-agent debugging over Band channels._`);

  return lines.join("\n");
}

export function downloadBlob(filename: string, content: string | Blob, mime?: string): void {
  const blob = content instanceof Blob ? content : new Blob([content], { type: mime || "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function buildPdfReport(session: DebugSession): Promise<Blob> {
  // Dynamic import keeps jsPDF out of the initial bundle
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentW = pageW - margin * 2;
  let y = margin;

  const ensure = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const writeWrapped = (text: string, opts: { size?: number; bold?: boolean; mono?: boolean; color?: [number, number, number]; lineGap?: number } = {}) => {
    const size = opts.size ?? 10;
    doc.setFont(opts.mono ? "courier" : "helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(...(opts.color ?? [30, 30, 35]));
    const lines = doc.splitTextToSize(text, contentW) as string[];
    const lineHeight = size * 1.25;
    for (const line of lines) {
      ensure(lineHeight);
      doc.text(line, margin, y);
      y += lineHeight;
    }
    y += opts.lineGap ?? 2;
  };

  const hr = () => {
    ensure(10);
    doc.setDrawColor(220, 220, 230);
    doc.line(margin, y, pageW - margin, y);
    y += 10;
  };

  const codeBlock = (label: string, code: string) => {
    writeWrapped(label, { size: 9, bold: true, color: [110, 110, 130] });
    const lines = doc.splitTextToSize(code, contentW - 12) as string[];
    const lineHeight = 9 * 1.3;
    const blockH = Math.min(lines.length, 60) * lineHeight + 12;
    ensure(blockH + 4);
    doc.setFillColor(245, 245, 250);
    doc.setDrawColor(225, 225, 235);
    doc.roundedRect(margin, y, contentW, 0, 0, 0); // placeholder; we draw per chunk instead

    // Draw chunked to support overflow across pages
    let i = 0;
    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    doc.setTextColor(40, 40, 55);
    while (i < lines.length) {
      const remaining = lines.length - i;
      const fit = Math.floor((pageH - margin - y - 8) / lineHeight);
      const take = Math.max(1, Math.min(remaining, Math.max(fit, 1)));
      const bh = take * lineHeight + 8;
      doc.setFillColor(245, 245, 250);
      doc.setDrawColor(225, 225, 235);
      doc.roundedRect(margin, y, contentW, bh, 4, 4, "FD");
      for (let k = 0; k < take; k++) {
        doc.text(lines[i + k], margin + 6, y + 6 + (k + 1) * lineHeight - 3);
      }
      y += bh + 4;
      i += take;
      if (i < lines.length) {
        doc.addPage();
        y = margin;
      }
    }
  };

  // --- Cover header ---
  doc.setFillColor(15, 12, 30);
  doc.rect(0, 0, pageW, 90, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("BandFix AI — Debug Report", margin, 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(180, 180, 210);
  doc.text(`Session ${session.id}`, margin, 70);
  y = 110;

  writeWrapped(session.input.title, { size: 16, bold: true });
  writeWrapped(
    `Language: ${session.input.language}  •  Started: ${fmtTime(session.createdAt)}  •  Duration: ${fmtDuration(session.durationMs)}  •  Status: ${session.status}`,
    { size: 9, color: [110, 110, 130] },
  );
  hr();

  // --- Bug report ---
  writeWrapped("Bug Finder", { size: 14, bold: true });
  if (session.bugReport) {
    writeWrapped(`Root cause: ${session.bugReport.rootCause}`, { bold: true });
    writeWrapped(`Severity: ${session.bugReport.severity}`, { size: 9, color: [110, 110, 130] });
    writeWrapped(session.bugReport.explanation);
  } else {
    writeWrapped("No bug report produced.", { color: [150, 150, 160] });
  }
  hr();

  // --- Fix ---
  writeWrapped("Fix Generator", { size: 14, bold: true });
  if (session.fix) {
    writeWrapped(`Changes (${session.fix.changes.length}):`, { bold: true });
    for (const c of session.fix.changes) writeWrapped(`• ${c}`);
    y += 4;
    codeBlock("Original code", session.input.code);
    codeBlock("Fixed code", session.fix.fixedCode);
  } else {
    writeWrapped("No fix produced.", { color: [150, 150, 160] });
  }
  hr();

  // --- Review ---
  writeWrapped("Reviewer", { size: 14, bold: true });
  if (session.review) {
    writeWrapped(`Status: ${session.review.status}  •  Score: ${session.review.score}/100`, { bold: true });
    writeWrapped(`Security: ${session.review.securityNote}`);
    writeWrapped(`Performance: ${session.review.performanceNote}`);
    writeWrapped(`Recommendation: ${session.review.recommendation}`);
  } else {
    writeWrapped("No review produced.", { color: [150, 150, 160] });
  }
  hr();

  // --- Band transcript ---
  writeWrapped("Band Channel Transcript", { size: 14, bold: true });
  session.messages.forEach((m, i) => {
    const route = m.to ? `${m.from} → ${m.to}` : String(m.from);
    writeWrapped(
      `${String(i + 1).padStart(2, "0")}  ${new Date(m.timestamp).toISOString().slice(11, 23)}  ${m.channel}  (${route})`,
      { size: 9, bold: true, color: [90, 60, 180], mono: true, lineGap: 0 },
    );
    writeWrapped(m.text, { size: 10, lineGap: 6 });
  });

  return doc.output("blob");
}

export function reportFilename(session: DebugSession, ext: "md" | "pdf" | "json"): string {
  const slug = (session.input.title || "bandfix")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "bandfix";
  return `${slug}-${session.id}.${ext}`;
}
