/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellHistoryRouteImport } from './routes/_shell.history'
import { Route as ShellCreateRouteImport } from './routes/_shell.create'
import { Route as ShellCppTerminalRouteImport } from './routes/_shell.cpp-terminal'
import { Route as ShellBandLogsRouteImport } from './routes/_shell.band-logs'
import { Route as ShellAgentsRouteImport } from './routes/_shell.agents'
import { Route as ShellRunIdRouteImport } from './routes/_shell.run.$id'
import { Route as ShellResultIdRouteImport } from './routes/_shell.result.$id'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellHistoryRoute = ShellHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCreateRoute = ShellCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCppTerminalRoute = ShellCppTerminalRouteImport.update({
  id: '/cpp-terminal',
  path: '/cpp-terminal',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBandLogsRoute = ShellBandLogsRouteImport.update({
  id: '/band-logs',
  path: '/band-logs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAgentsRoute = ShellAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRunIdRoute = ShellRunIdRouteImport.update({
  id: '/run/$id',
  path: '/run/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResultIdRoute = ShellResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof ShellAgentsRoute
  '/band-logs': typeof ShellBandLogsRoute
  '/cpp-terminal': typeof ShellCppTerminalRoute
  '/create': typeof ShellCreateRoute
  '/history': typeof ShellHistoryRoute
  '/result/$id': typeof ShellResultIdRoute
  '/run/$id': typeof ShellRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof ShellAgentsRoute
  '/band-logs': typeof ShellBandLogsRoute
  '/cpp-terminal': typeof ShellCppTerminalRoute
  '/create': typeof ShellCreateRoute
  '/history': typeof ShellHistoryRoute
  '/result/$id': typeof ShellResultIdRoute
  '/run/$id': typeof ShellRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/agents': typeof ShellAgentsRoute
  '/_shell/band-logs': typeof ShellBandLogsRoute
  '/_shell/cpp-terminal': typeof ShellCppTerminalRoute
  '/_shell/create': typeof ShellCreateRoute
  '/_shell/history': typeof ShellHistoryRoute
  '/_shell/result/$id': typeof ShellResultIdRoute
  '/_shell/run/$id': typeof ShellRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/band-logs'
    | '/cpp-terminal'
    | '/create'
    | '/history'
    | '/result/$id'
    | '/run/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/band-logs'
    | '/cpp-terminal'
    | '/create'
    | '/history'
    | '/result/$id'
    | '/run/$id'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/agents'
    | '/_shell/band-logs'
    | '/_shell/cpp-terminal'
    | '/_shell/create'
    | '/_shell/history'
    | '/_shell/result/$id'
    | '/_shell/run/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/history': {
      id: '/_shell/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ShellHistoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/create': {
      id: '/_shell/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof ShellCreateRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cpp-terminal': {
      id: '/_shell/cpp-terminal'
      path: '/cpp-terminal'
      fullPath: '/cpp-terminal'
      preLoaderRoute: typeof ShellCppTerminalRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/band-logs': {
      id: '/_shell/band-logs'
      path: '/band-logs'
      fullPath: '/band-logs'
      preLoaderRoute: typeof ShellBandLogsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/agents': {
      id: '/_shell/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof ShellAgentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/run/$id': {
      id: '/_shell/run/$id'
      path: '/run/$id'
      fullPath: '/run/$id'
      preLoaderRoute: typeof ShellRunIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/result/$id': {
      id: '/_shell/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ShellResultIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAgentsRoute: typeof ShellAgentsRoute
  ShellBandLogsRoute: typeof ShellBandLogsRoute
  ShellCppTerminalRoute: typeof ShellCppTerminalRoute
  ShellCreateRoute: typeof ShellCreateRoute
  ShellHistoryRoute: typeof ShellHistoryRoute
  ShellResultIdRoute: typeof ShellResultIdRoute
  ShellRunIdRoute: typeof ShellRunIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAgentsRoute: ShellAgentsRoute,
  ShellBandLogsRoute: ShellBandLogsRoute,
  ShellCppTerminalRoute: ShellCppTerminalRoute,
  ShellCreateRoute: ShellCreateRoute,
  ShellHistoryRoute: ShellHistoryRoute,
  ShellResultIdRoute: ShellResultIdRoute,
  ShellRunIdRoute: ShellRunIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
